services:
  mattermost:
    image: mattermost/mattermost-preview
    container_name: mattermost
    ports:
      - "8065:8065"
    environment:
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"

  tarantool:
    image: tarantool/tarantool
    container_name: tarantool
    ports:
      - "3301:3301"
    volumes:
      - ./init.lua:/opt/tarantool/init.lua
    command: [ "tarantool", "/opt/tarantool/init.lua" ]

  bot:
    build: .
    container_name: bot
    env_file:
      - .env
    depends_on:
      - tarantool
    ports:
      - "8080:8080"